version: "3"

services:
  # neo4j db service
  cp_db:
    # build: ./db
    image: xhuliodo/couch-potatoes-db:v0.1
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      # - NEO4J_apoc_import_file_enabled=true
      # - NEO4J_apoc_export_file_enabled=true
      # - NEO4J_dbms_shell_enabled=true
    # volumes: 
    # - "./db/conf:/conf"
    # - "./db/data:/data"
  
  # nodejs graphql api
  # cp_api:
  #   build: ./api
  #   ports:
  #     - 4001:4001
  #   environment:
  #     - NEO4J_URI=bolt://cp_db:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=letmein
  #     - GRAPHQL_LISTEN_PORT=4001
  #     - GRAPHQL_URI=http://cp_api:4001/graphql
  #   depends_on:
  #     - cp_db