version: "3"

services:
  # neo4j db service
  cp-db:
    # build: ./db
    image: xhuliodo/couch-potatoes-db:latest
    container_name: cp-db
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      # - NEO4J_apoc_import_file_enabled=true
      # - NEO4J_apoc_export_file_enabled=true
      # - NEO4J_dbms_shell_enabled=true
    volumes: 
    # - "./db/conf:/conf"
    - "./db/data:/data"
    - "./db/import:/import"
    # this one below worked on as a command inside the container
    # command: bash -c "cypher-shell -u neo4j -p letmein -f /import/import.cypher"
  
  # nodejs graphql api
  cp-api:
    build: ./api
    container_name: cp-api
    ports:
      - 4001:4001
    environment:
      - NEO4J_URI=bolt://cp-db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=letmein
      - GRAPHQL_LISTEN_PORT=4001
      - GRAPHQL_URI=http://cp-api:4001/graphql
    depends_on:
      - cp-db

  # react client
  cp-client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      args: 
        REACT_APP_API_ENDPOINT: ${REACT_APP_API_ENDPOINT}
        REACT_APP_DOMAIN: ${REACT_APP_DOMAIN}
    ports:
      - 4000:80
