basePath: /
consumes:
- application/json
host: localhost
info:
  description: Docs for Movies API
  title: Clean Potatoes API
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"
