name: Go

on:
  workflow_dispatch:
  push:
    branches: 
    - master
    paths:
      - "clean-api/**"
    
  pull_request:
    branches: 
    - master
    paths:
      - "clean-api/**"
      
jobs:
  ci:
    env:
      working-directory: ./clean-api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Get dependencies
      run: go get
      working-directory: ${{env.working-directory}}

    - name: Build
      run: go build -v ./...
      working-directory: ${{env.working-directory}}

    - name: Test
      run: go test -v ./...
      working-directory: ${{env.working-directory}}

    - name: Docs
      run: make install_swag && make create_docs
      working-directory: ${{env.working-directory}}

