name: Go

on:
  workflow_dispatch:
  push:
    branches: 
    - master/clean-api/**
  pull_request:
    branches: 
    - master/clean-api/**

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Docs
      run: make install_swag && make create_docs
